# Generated by Django 4.2.1 on 2023-11-03 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=25, verbose_name='Motivo')),
                ('descricao', models.TextField(default='Sem Descrição', max_length=1000, verbose_name='Descrição')),
                ('tipo_emocao', models.CharField(choices=[('Irritado 😡', 'Irritado 😡'), ('Triste 😢', 'Triste 😢'), ('Medo 😰', 'Medo 😰'), ('Feliz 😊', 'Feliz 😊'), ('Nojo 🤢', 'Nojo 🤢')], max_length=100, verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Atualização')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emoção',
                'verbose_name_plural': 'Emoções',
            },
        ),
    ]
