# Generated by Django 4.2.1 on 2023-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Ensino Superior', 'ensino_superior'), ('Ensino Médio', 'ensino_medio'), ('Pós Graduação', 'pos_graducao')], max_length=20, null=True, verbose_name='Nível'),
        ),
    ]
