# Generated by Django 4.2.1 on 2023-09-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='modalidade',
        ),
        migrations.AddField(
            model_name='curso',
            name='ano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ano', verbose_name='Ano/Período'),
        ),
    ]
