# Generated by Django 4.2.1 on 2023-09-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_curso_usuario_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='usuario_criacao',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='usuario_criacao',
        ),
    ]
