# Generated by Django 4.2.1 on 2023-09-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_turma_usuario_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidade',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='modalidade',
            name='usuario_criacao',
        ),
    ]
