# Generated by Django 4.2.1 on 2023-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='localidade',
            field=models.CharField(blank=True, choices=[('Zona Rural', 'Zona Rural'), ('Zona Hurbana', 'Zona Hurbana')], max_length=40, null=True),
        ),
    ]
