# Generated by Django 4.2.1 on 2023-09-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_etnia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.etnia'),
        ),
    ]
