# Generated by Django 4.2.1 on 2023-09-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_etnia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'ClasseSocial',
                'verbose_name_plural': 'Classe Social',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='user',
            name='religiao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Religiao'),
        ),
        migrations.AddField(
            model_name='user',
            name='classe_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classesocial', verbose_name='Classe Social'),
        ),
    ]
