# Generated by Django 4.2.1 on 2023-09-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_classesocial_user_matricula_user_religiao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.etnia', verbose_name='Etnia'),
        ),
    ]
