# Generated by Django 4.2.1 on 2023-09-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_modalidade_usuario_atualizacao_and_more'),
        ('accounts', '0007_userprofile_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='curso',
        ),
        migrations.AddField(
            model_name='user',
            name='ano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ano', verbose_name='Ano/Período'),
        ),
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Curso'),
        ),
    ]
