# Generated by Django 4.2.1 on 2023-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='localidade',
            field=models.CharField(blank=True, choices=[('Zona Rural', 'Zona Rural'), ('Zona Hurbana', 'Zona Urbana')], max_length=40, null=True),
        ),
    ]
