# Generated by Django 4.2.1 on 2023-12-11 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_turma_ano'),
        ('accounts', '0012_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='relatorio_images')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('relatorio', models.TextField(verbose_name='Relatório')),
                ('psicologo', models.ForeignKey(limit_choices_to={'role': 'Psicologo'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Relatório Psicológico',
                'verbose_name_plural': 'Relatórios Psicológicos',
            },
        ),
    ]
