# Generated by Django 4.2.1 on 2023-09-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_criacao',
        ),
    ]
