# Generated by Django 4.2.1 on 2023-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_remove_categoria_usuario_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='texto',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
