# Generated by Django 4.2.1 on 2023-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_categoria_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='embed_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
